const { addDoc, collection, getFirestore } = require("firebase/firestore");
const { app } = require("./firebaseConfig.node.js");

const db = getFirestore(app);

const sampleTours = [
  {
    name: "Skardu Valley Expedition",
    description:
      "Explore the stunning landscapes of Skardu, including the famous Shangrila Resort and Kachura Lake.",
    rating: 4.9,
    price: "60000",
    duration: "6",
    location: "Skardu, Gilgit-Baltistan",
    category: "Mountains",
    startingPoint: "Islamabad",
    latitude: 35.2971,
    longitude: 75.6337,
    departureDate: "2024-08-01",
    endingDate: "2024-08-07",
    itinerary: [
      {
        time: "Day 1, 7:00 AM",
        place: "Islamabad Departure",
        description:
          "Travel from Islamabad to Skardu via the Karakoram Highway.",
        price: "4000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 10:00 AM",
        place: "Shangrila Resort",
        description: "Visit the famous Shangrila Resort and Kachura Lake.",
        price: "3000 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Mohenjo-daro Heritage Tour",
    description:
      "Discover the ancient ruins of Mohenjo-daro, a UNESCO World Heritage site.",
    rating: 4.5,
    price: "20000",
    duration: "2",
    location: "Mohenjo-daro, Sindh",
    category: "Historical Sites",
    startingPoint: "Karachi",
    latitude: 27.3292,
    longitude: 68.1389,
    departureDate: "2024-09-15",
    endingDate: "2024-09-17",
    itinerary: [
      {
        time: "Day 1, 8:00 AM",
        place: "Karachi Departure",
        description: "Travel to Mohenjo-daro by road.",
        price: "2500 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 9:00 AM",
        place: "Mohenjo-daro Ruins",
        description: "Guided tour of the ancient ruins.",
        price: "1000 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Hingol National Park Safari",
    description:
      "Experience the unique landscapes and wildlife of Hingol National Park.",
    rating: 4.7,
    price: "35000",
    duration: "3",
    location: "Hingol, Balochistan",
    category: "Adventure",
    startingPoint: "Karachi",
    latitude: 25.5,
    longitude: 65.5,
    departureDate: "2024-10-10",
    endingDate: "2024-10-13",
    itinerary: [
      {
        time: "Day 1, 7:00 AM",
        place: "Karachi Departure",
        description: "Travel to Hingol National Park.",
        price: "3000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 9:00 AM",
        place: "Wildlife Safari",
        description: "Safari tour to spot wildlife and unique rock formations.",
        price: "5000 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Kalam Valley Retreat",
    description:
      "Escape to the serene Kalam Valley, known for its lush greenery and waterfalls.",
    rating: 4.8,
    price: "45000",
    duration: "4",
    location: "Kalam, Khyber Pakhtunkhwa",
    category: "Mountains",
    startingPoint: "Islamabad",
    latitude: 35.4833,
    longitude: 72.5833,
    departureDate: "2024-07-05",
    endingDate: "2024-07-09",
    itinerary: [
      {
        time: "Day 1, 6:00 AM",
        place: "Islamabad Departure",
        description: "Travel to Kalam Valley via Swat.",
        price: "2500 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 10:00 AM",
        place: "Kalam Waterfalls",
        description:
          "Visit the beautiful waterfalls and enjoy the scenic views.",
        price: "0 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Makli Necropolis Tour",
    description:
      "Explore the historic Makli Necropolis, one of the largest funerary sites in the world.",
    rating: 4.4,
    price: "15000",
    duration: "2",
    location: "Thatta, Sindh",
    category: "Historical Sites",
    startingPoint: "Karachi",
    latitude: 24.75,
    longitude: 67.9,
    departureDate: "2024-11-05",
    endingDate: "2024-11-07",
    itinerary: [
      {
        time: "Day 1, 9:00 AM",
        place: "Karachi Departure",
        description: "Travel to Thatta to visit Makli Necropolis.",
        price: "2000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 10:00 AM",
        place: "Makli Necropolis",
        description: "Guided tour of the historic tombs and monuments.",
        price: "500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Ratti Gali Lake Trek",
    description:
      "Trek to the mesmerizing Ratti Gali Lake, known for its emerald waters and surrounding alpine meadows.",
    rating: 4.7,
    price: "40000",
    duration: "4",
    location: "Neelum Valley, Azad Kashmir",
    category: "Lakes",
    startingPoint: "Islamabad",
    latitude: 34.6833,
    longitude: 74.0833,
    departureDate: "2024-09-05",
    endingDate: "2024-09-09",
    itinerary: [
      {
        time: "Day 1, 6:00 AM",
        place: "Islamabad Departure",
        description: "Travel to Neelum Valley",
        price: "3000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 8:00 AM",
        place: "Lake Trek",
        description: "Trek to Ratti Gali Lake through beautiful trails",
        price: "2000 PKR",
        type: "trek",
      },
      {
        time: "Day 3, 9:00 AM",
        place: "Lake Exploration",
        description: "Explore the lake and surrounding meadows",
        price: "1500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Harappa Archaeological Tour",
    description:
      "Visit the ancient ruins of Harappa, a significant archaeological site.",
    rating: 4.3,
    price: "18000",
    duration: "2",
    location: "Harappa, Punjab",
    category: "Historical Sites",
    startingPoint: "Lahore",
    latitude: 30.6333,
    longitude: 72.8667,
    departureDate: "2024-10-20",
    endingDate: "2024-10-22",
    itinerary: [
      {
        time: "Day 1, 8:00 AM",
        place: "Lahore Departure",
        description: "Travel to Harappa to explore the archaeological site.",
        price: "2000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 9:00 AM",
        place: "Harappa Ruins",
        description: "Guided tour of the ancient ruins and museum.",
        price: "1000 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Kala Chitta Forest Expedition",
    description:
      "Explore the ancient Kala Chitta mountain range and its dense forests, home to diverse wildlife and natural springs.",
    rating: 4.6,
    price: "30000",
    duration: "2",
    location: "Attock, Punjab",
    category: "Forests",
    startingPoint: "Islamabad",
    latitude: 33.7667,
    longitude: 72.3667,
    departureDate: "2024-10-05",
    endingDate: "2024-10-07",
    itinerary: [
      {
        time: "Day 1, 7:00 AM",
        place: "Islamabad Departure",
        description: "Travel to Kala Chitta Forest Range",
        price: "2000 PKR",
        type: "transport",
      },
      {
        time: "Day 1, 10:00 AM",
        place: "Forest Trail",
        description: "Guided hike through the forest trails",
        price: "1500 PKR",
        type: "trek",
      },
      {
        time: "Day 2, 9:00 AM",
        place: "Natural Springs",
        description: "Visit the natural springs and picnic spots",
        price: "1000 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Changa Manga Forest Adventure",
    description:
      "Experience the largest man-made forest in Pakistan, featuring wildlife, boating, and nature trails.",
    rating: 4.6,
    price: "25000",
    duration: "2",
    location: "Changa Manga, Punjab",
    category: "Forests",
    startingPoint: "Lahore",
    latitude: 31.0833,
    longitude: 73.9667,
    departureDate: "2024-09-01",
    endingDate: "2024-09-03",
    itinerary: [
      {
        time: "Day 1, 8:00 AM",
        place: "Lahore Departure",
        description: "Travel to Changa Manga Forest Reserve",
        price: "1500 PKR",
        type: "transport",
      },
      {
        time: "Day 1, 11:00 AM",
        place: "Forest Safari",
        description: "Guided safari through the forest to spot wildlife",
        price: "2000 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 2, 9:00 AM",
        place: "Boating and Nature Walk",
        description: "Enjoy boating in the lake and explore nature trails",
        price: "1500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Ayubia National Park Explorer",
    description:
      "Discover the beautiful pine forests and wildlife of Ayubia National Park in the Murree Hills.",
    rating: 4.7,
    price: "35000",
    duration: "3",
    location: "Ayubia, Khyber Pakhtunkhwa",
    category: "Forests",
    startingPoint: "Islamabad",
    latitude: 33.8667,
    longitude: 73.1333,
    departureDate: "2024-10-15",
    endingDate: "2024-10-18",
    itinerary: [
      {
        time: "Day 1, 7:00 AM",
        place: "Islamabad Departure",
        description: "Travel to Ayubia National Park",
        price: "2000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 9:00 AM",
        place: "Pine Forest Trek",
        description: "Guided trek through the pine forests",
        price: "1500 PKR",
        type: "trek",
      },
      {
        time: "Day 3, 10:00 AM",
        place: "Wildlife Watching",
        description: "Spot local wildlife and bird watching",
        price: "1000 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Chitral Gol National Park Safari",
    description:
      "Explore the pristine forests and wildlife of Chitral Gol National Park, home to the rare Markhor.",
    rating: 4.8,
    price: "55000",
    duration: "4",
    location: "Chitral, Khyber Pakhtunkhwa",
    category: "Forests",
    startingPoint: "Peshawar",
    latitude: 35.9167,
    longitude: 71.7833,
    departureDate: "2024-08-10",
    endingDate: "2024-08-14",
    itinerary: [
      {
        time: "Day 1, 6:00 AM",
        place: "Peshawar Departure",
        description: "Travel to Chitral via Lowari Pass",
        price: "4000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 8:00 AM",
        place: "Forest Safari",
        description: "Wildlife safari in the national park",
        price: "3000 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 3, 9:00 AM",
        place: "Nature Trail",
        description: "Guided nature walk through the forest",
        price: "2000 PKR",
        type: "trek",
      },
    ],
  },
  {
    name: "Margalla Hills Forest Trail",
    description:
      "Experience the beautiful trails and wildlife of Margalla Hills National Park, right next to Islamabad.",
    rating: 4.5,
    price: "15000",
    duration: "1",
    location: "Islamabad Capital Territory",
    category: "Forests",
    startingPoint: "Islamabad",
    latitude: 33.7167,
    longitude: 72.9833,
    departureDate: "2024-09-20",
    endingDate: "2024-09-21",
    itinerary: [
      {
        time: "Day 1, 7:00 AM",
        place: "Trail 3 Start",
        description: "Begin the hike from Trail 3",
        price: "0 PKR",
        type: "trek",
      },
      {
        time: "Day 1, 10:00 AM",
        place: "Monkey Point",
        description: "Visit Monkey Point and enjoy panoramic views",
        price: "0 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 1, 2:00 PM",
        place: "Pir Sohawa",
        description: "Lunch at Pir Sohawa with scenic views",
        price: "2000 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Kirthar National Park Safari",
    description:
      "Experience the unique desert forest ecosystem of Kirthar National Park, home to rare wildlife species.",
    rating: 4.7,
    price: "40000",
    duration: "3",
    location: "Jamshoro, Sindh",
    category: "Forests",
    startingPoint: "Karachi",
    latitude: 25.5833,
    longitude: 67.5833,
    departureDate: "2024-11-10",
    endingDate: "2024-11-13",
    itinerary: [
      {
        time: "Day 1, 6:00 AM",
        place: "Karachi Departure",
        description: "Travel to Kirthar National Park",
        price: "3000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 8:00 AM",
        place: "Wildlife Safari",
        description: "Safari to spot rare wildlife species",
        price: "2500 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 3, 9:00 AM",
        place: "Desert Forest Trail",
        description: "Explore the unique desert forest ecosystem",
        price: "2000 PKR",
        type: "trek",
      },
    ],
  },
  {
    name: "Lal Suhanra National Park Tour",
    description:
      "Discover the unique forest ecosystem of Lal Suhanra, featuring desert forests and wildlife sanctuary.",
    rating: 4.5,
    price: "28000",
    duration: "2",
    location: "Bahawalpur, Punjab",
    category: "Forests",
    startingPoint: "Lahore",
    latitude: 29.3333,
    longitude: 72.0167,
    departureDate: "2024-09-25",
    endingDate: "2024-09-27",
    itinerary: [
      {
        time: "Day 1, 7:00 AM",
        place: "Lahore Departure",
        description: "Travel to Lal Suhanra National Park",
        price: "2500 PKR",
        type: "transport",
      },
      {
        time: "Day 1, 11:00 AM",
        place: "Forest Safari",
        description: "Guided safari through the forest area",
        price: "2000 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 2, 9:00 AM",
        place: "Wildlife Sanctuary",
        description: "Visit the wildlife sanctuary and bird watching",
        price: "1500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Machiara National Park Trek",
    description:
      "Experience the beautiful forests and wildlife of Machiara National Park in Azad Kashmir.",
    rating: 4.8,
    price: "45000",
    duration: "4",
    location: "Muzaffarabad, Azad Kashmir",
    category: "Forests",
    startingPoint: "Islamabad",
    latitude: 34.5167,
    longitude: 73.5167,
    departureDate: "2024-08-15",
    endingDate: "2024-08-19",
    itinerary: [
      {
        time: "Day 1, 6:00 AM",
        place: "Islamabad Departure",
        description: "Travel to Machiara National Park",
        price: "3000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 8:00 AM",
        place: "Forest Trek",
        description: "Guided trek through the forest trails",
        price: "2000 PKR",
        type: "trek",
      },
      {
        time: "Day 3, 9:00 AM",
        place: "Wildlife Watching",
        description: "Spot rare wildlife and bird species",
        price: "1500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Saiful Muluk Lake Expedition",
    description:
      "Experience the crystal-clear waters of Saiful Muluk Lake, surrounded by snow-capped peaks in the Kaghan Valley.",
    rating: 4.9,
    price: "45000",
    duration: "4",
    location: "Kaghan Valley, Khyber Pakhtunkhwa",
    category: "Lakes",
    startingPoint: "Islamabad",
    latitude: 34.8833,
    longitude: 73.7,
    departureDate: "2024-07-15",
    endingDate: "2024-07-19",
    itinerary: [
      {
        time: "Day 1, 6:00 AM",
        place: "Islamabad Departure",
        description: "Travel to Kaghan Valley via Mansehra",
        price: "3000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 9:00 AM",
        place: "Lake Trek",
        description: "Trek to Saiful Muluk Lake with scenic views",
        price: "2000 PKR",
        type: "trek",
      },
      {
        time: "Day 3, 10:00 AM",
        place: "Lake Activities",
        description: "Enjoy boating and photography at the lake",
        price: "1500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Attabad Lake Adventure",
    description:
      "Explore the stunning turquoise waters of Attabad Lake, formed by a natural landslide in Hunza Valley.",
    rating: 4.8,
    price: "50000",
    duration: "5",
    location: "Hunza Valley, Gilgit-Baltistan",
    category: "Lakes",
    startingPoint: "Islamabad",
    latitude: 36.3167,
    longitude: 74.8167,
    departureDate: "2024-08-10",
    endingDate: "2024-08-15",
    itinerary: [
      {
        time: "Day 1, 7:00 AM",
        place: "Islamabad Departure",
        description: "Travel to Hunza Valley via Karakoram Highway",
        price: "4000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 10:00 AM",
        place: "Lake Cruise",
        description: "Enjoy a scenic boat ride on Attabad Lake",
        price: "3000 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 3, 9:00 AM",
        place: "Water Activities",
        description: "Experience kayaking and fishing at the lake",
        price: "2500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Dudipatsar Lake Expedition",
    description:
      "Discover the pristine Dudipatsar Lake, also known as the White Pearl Lake, in the Kaghan Valley.",
    rating: 4.8,
    price: "42000",
    duration: "4",
    location: "Kaghan Valley, Khyber Pakhtunkhwa",
    category: "Lakes",
    startingPoint: "Islamabad",
    latitude: 35.0833,
    longitude: 73.8833,
    departureDate: "2024-07-20",
    endingDate: "2024-07-24",
    itinerary: [
      {
        time: "Day 1, 6:00 AM",
        place: "Islamabad Departure",
        description: "Travel to Kaghan Valley",
        price: "3000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 8:00 AM",
        place: "Lake Trek",
        description: "Trek to Dudipatsar Lake through scenic trails",
        price: "2000 PKR",
        type: "trek",
      },
      {
        time: "Day 3, 10:00 AM",
        place: "Lake Activities",
        description: "Enjoy photography and nature walks around the lake",
        price: "1500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Rush Lake Adventure",
    description:
      "Experience the highest alpine lake in Pakistan, Rush Lake, surrounded by stunning mountain peaks.",
    rating: 4.9,
    price: "55000",
    duration: "6",
    location: "Nagarparkar, Sindh",
    category: "Lakes",
    startingPoint: "Karachi",
    latitude: 24.6667,
    longitude: 70.2833,
    departureDate: "2024-08-25",
    endingDate: "2024-08-31",
    itinerary: [
      {
        time: "Day 1, 7:00 AM",
        place: "Karachi Departure",
        description: "Travel to Nagarparkar",
        price: "4000 PKR",
        type: "transport",
      },
      {
        time: "Day 2, 8:00 AM",
        place: "Base Camp",
        description: "Set up base camp near Rush Lake",
        price: "2000 PKR",
        type: "trek",
      },
      {
        time: "Day 3, 9:00 AM",
        place: "Lake Exploration",
        description: "Explore the lake and surrounding peaks",
        price: "2500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Lahore Heritage Explorer",
    description:
      "Discover the rich cultural heritage of Lahore, from Mughal monuments to vibrant food streets and traditional bazaars.",
    rating: 4.8,
    price: "25000",
    duration: "3",
    location: "Lahore, Punjab",
    category: "Cities",
    startingPoint: "Lahore",
    latitude: 31.5497,
    longitude: 74.3436,
    departureDate: "2024-09-10",
    endingDate: "2024-09-13",
    itinerary: [
      {
        time: "Day 1, 9:00 AM",
        place: "Lahore Fort",
        description: "Explore the historic Lahore Fort and Badshahi Mosque",
        price: "1000 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 1, 2:00 PM",
        place: "Food Street",
        description: "Lunch at the famous Food Street with local delicacies",
        price: "2000 PKR",
        type: "food",
      },
      {
        time: "Day 2, 10:00 AM",
        place: "Walled City",
        description: "Guided tour of the historic Walled City and its bazaars",
        price: "1500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Karachi Coastal City Tour",
    description:
      "Experience the vibrant city life of Karachi, from beautiful beaches to historic sites and modern attractions.",
    rating: 4.7,
    price: "30000",
    duration: "3",
    location: "Karachi, Sindh",
    category: "Cities",
    startingPoint: "Karachi",
    latitude: 24.8607,
    longitude: 67.0011,
    departureDate: "2024-10-05",
    endingDate: "2024-10-08",
    itinerary: [
      {
        time: "Day 1, 10:00 AM",
        place: "Clifton Beach",
        description: "Visit Clifton Beach and enjoy water activities",
        price: "2000 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 2, 11:00 AM",
        place: "Mohatta Palace",
        description: "Explore the historic Mohatta Palace and its museum",
        price: "1000 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 3, 2:00 PM",
        place: "Port Grand",
        description: "Enjoy food and entertainment at Port Grand",
        price: "2500 PKR",
        type: "food",
      },
    ],
  },
  {
    name: "Islamabad Modern City Experience",
    description:
      "Discover Pakistan's beautiful capital city, from modern architecture to scenic viewpoints and cultural centers.",
    rating: 4.6,
    price: "20000",
    duration: "2",
    location: "Islamabad Capital Territory",
    category: "Cities",
    startingPoint: "Islamabad",
    latitude: 33.6844,
    longitude: 73.0479,
    departureDate: "2024-09-15",
    endingDate: "2024-09-17",
    itinerary: [
      {
        time: "Day 1, 9:00 AM",
        place: "Faisal Mosque",
        description: "Visit the iconic Faisal Mosque",
        price: "0 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 1, 2:00 PM",
        place: "Daman-e-Koh",
        description: "Enjoy panoramic views of Islamabad from Daman-e-Koh",
        price: "0 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 2, 10:00 AM",
        place: "Lok Virsa Museum",
        description: "Explore Pakistan's cultural heritage at Lok Virsa",
        price: "500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Peshawar Old City Tour",
    description:
      "Experience the ancient city of Peshawar, known for its historic bazaars, traditional food, and rich cultural heritage.",
    rating: 4.7,
    price: "28000",
    duration: "3",
    location: "Peshawar, Khyber Pakhtunkhwa",
    category: "Cities",
    startingPoint: "Peshawar",
    latitude: 34.015,
    longitude: 71.5249,
    departureDate: "2024-10-20",
    endingDate: "2024-10-23",
    itinerary: [
      {
        time: "Day 1, 10:00 AM",
        place: "Qissa Khwani Bazaar",
        description: "Explore the historic Qissa Khwani Bazaar",
        price: "0 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 2, 11:00 AM",
        place: "Peshawar Museum",
        description: "Visit the Peshawar Museum and learn about local history",
        price: "500 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 3, 1:00 PM",
        place: "Traditional Food Tour",
        description: "Experience authentic Peshawari cuisine",
        price: "2000 PKR",
        type: "food",
      },
    ],
  },
  {
    name: "Multan Sufi Heritage Tour",
    description:
      "Discover the City of Saints, exploring historic shrines, traditional crafts, and rich Sufi culture.",
    rating: 4.6,
    price: "22000",
    duration: "2",
    location: "Multan, Punjab",
    category: "Cities",
    startingPoint: "Multan",
    latitude: 30.1575,
    longitude: 71.5249,
    departureDate: "2024-11-05",
    endingDate: "2024-11-07",
    itinerary: [
      {
        time: "Day 1, 9:00 AM",
        place: "Shah Rukn-e-Alam Shrine",
        description: "Visit the historic shrine and learn about Sufi culture",
        price: "0 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 1, 2:00 PM",
        place: "Multan Bazaar",
        description: "Explore traditional crafts and local markets",
        price: "0 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 2, 10:00 AM",
        place: "Multan Fort",
        description: "Tour the historic Multan Fort",
        price: "500 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Clifton Beach Paradise",
    description:
      "Experience the vibrant atmosphere of Karachi's most popular beach, featuring water sports, camel rides, and stunning sunsets.",
    rating: 4.7,
    price: "25000",
    duration: "2",
    location: "Karachi, Sindh",
    category: "Beaches",
    startingPoint: "Karachi",
    latitude: 24.8133,
    longitude: 66.975,
    departureDate: "2024-09-15",
    endingDate: "2024-09-17",
    itinerary: [
      {
        time: "Day 1, 4:00 PM",
        place: "Beach Activities",
        description: "Enjoy water sports and camel rides at Clifton Beach",
        price: "2000 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 1, 6:00 PM",
        place: "Sunset Viewing",
        description: "Watch the beautiful sunset over the Arabian Sea",
        price: "0 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 2, 10:00 AM",
        place: "Beach Sports",
        description: "Participate in beach volleyball and other activities",
        price: "1000 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "French Beach Escape",
    description:
      "Discover the pristine French Beach, known for its crystal-clear waters and peaceful atmosphere, perfect for a weekend getaway.",
    rating: 4.8,
    price: "30000",
    duration: "2",
    location: "Karachi, Sindh",
    category: "Beaches",
    startingPoint: "Karachi",
    latitude: 24.8333,
    longitude: 66.9167,
    departureDate: "2024-10-05",
    endingDate: "2024-10-07",
    itinerary: [
      {
        time: "Day 1, 11:00 AM",
        place: "Beach Arrival",
        description: "Arrive at French Beach and set up for the day",
        price: "0 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 1, 2:00 PM",
        place: "Water Activities",
        description: "Enjoy swimming and snorkeling in clear waters",
        price: "2500 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 2, 9:00 AM",
        place: "Beach Walk",
        description: "Morning walk along the pristine shoreline",
        price: "0 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Gadani Beach Adventure",
    description:
      "Experience the unique combination of beach activities and ship-breaking yard views at Gadani Beach.",
    rating: 4.6,
    price: "28000",
    duration: "2",
    location: "Gadani, Balochistan",
    category: "Beaches",
    startingPoint: "Karachi",
    latitude: 25.1167,
    longitude: 66.7167,
    departureDate: "2024-09-20",
    endingDate: "2024-09-22",
    itinerary: [
      {
        time: "Day 1, 10:00 AM",
        place: "Beach Activities",
        description: "Enjoy swimming and beach sports",
        price: "1500 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 1, 3:00 PM",
        place: "Ship-breaking View",
        description: "Visit the famous ship-breaking yard viewpoint",
        price: "1000 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 2, 9:00 AM",
        place: "Fishing Experience",
        description: "Try your hand at fishing with local fishermen",
        price: "2000 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Ormara Beach Retreat",
    description:
      "Escape to the serene Ormara Beach, known for its golden sands and peaceful atmosphere in Balochistan.",
    rating: 4.7,
    price: "35000",
    duration: "3",
    location: "Ormara, Balochistan",
    category: "Beaches",
    startingPoint: "Karachi",
    latitude: 25.2167,
    longitude: 64.6333,
    departureDate: "2024-10-15",
    endingDate: "2024-10-18",
    itinerary: [
      {
        time: "Day 1, 2:00 PM",
        place: "Beach Arrival",
        description: "Arrive at Ormara Beach and enjoy the sunset",
        price: "0 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 2, 10:00 AM",
        place: "Water Sports",
        description: "Enjoy various water activities and beach games",
        price: "3000 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 3, 9:00 AM",
        place: "Fishing Trip",
        description: "Experience deep-sea fishing with local guides",
        price: "4000 PKR",
        type: "tourist_spot",
      },
    ],
  },
  {
    name: "Hawks Bay Weekend",
    description:
      "Experience the perfect weekend getaway at Hawks Bay, known for its clean waters and family-friendly atmosphere.",
    rating: 4.6,
    price: "27000",
    duration: "2",
    location: "Karachi, Sindh",
    category: "Beaches",
    startingPoint: "Karachi",
    latitude: 24.8667,
    longitude: 66.8333,
    departureDate: "2024-09-25",
    endingDate: "2024-09-27",
    itinerary: [
      {
        time: "Day 1, 3:00 PM",
        place: "Beach Activities",
        description: "Enjoy swimming and beach sports",
        price: "1500 PKR",
        type: "tourist_spot",
      },
      {
        time: "Day 1, 6:00 PM",
        place: "BBQ Dinner",
        description: "Enjoy a beachside BBQ dinner",
        price: "2000 PKR",
        type: "food",
      },
      {
        time: "Day 2, 10:00 AM",
        place: "Water Sports",
        description: "Try various water sports activities",
        price: "2500 PKR",
        type: "tourist_spot",
      },
    ],
  },
];

const uploadToursToFirebase = async () => {
  try {
    const destinationsCollection = collection(db, "destinations");

    for (const tour of sampleTours) {
      const docRef = await addDoc(destinationsCollection, {
        ...tour,
        createdAt: new Date().toISOString(), // Adding createdAt field as it's used in queries
      });
      console.log(`Tour added with ID: ${docRef.id}`);
    }

    console.log("All tours uploaded successfully!");
  } catch (error) {
    console.error("Error uploading tours:", error);
  }
};

// Execute the upload
uploadToursToFirebase();
